# Generated by Django 5.1.5 on 2026-06-26 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=5)),
                ("bio", models.TextField(blank=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("pro", "Pro"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "risk_appetite",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
