# Generated by Django 5.1.5 on 2026-07-01 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_timescaledb_hypertable"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("price_above", "Price above"),
                            ("price_below", "Price below"),
                            ("pct_change", "Percent change"),
                            ("news_keyword", "News keyword"),
                            ("sentiment", "News sentiment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("once", "Once"), ("recurring", "Recurring")],
                        default="once",
                        max_length=10,
                    ),
                ),
                ("cooldown_seconds", models.PositiveIntegerField(default=0)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("priority", models.CharField(default="high", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="markets.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alert_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("suppressed", "Suppressed")],
                        default="sent",
                        max_length=12,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fires",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["user", "is_active"], name="alertrule_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["trigger_type", "is_active"], name="alertrule_trigger_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["user", "-triggered_at"], name="alert_user_time_idx"),
        ),
    ]
