# Generated by Django 5.1.5 on 2026-07-01 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_timescaledb_hypertable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prediction_type", models.CharField(max_length=30)),
                ("horizon", models.CharField(blank=True, max_length=10)),
                ("value", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("model", models.CharField(blank=True, max_length=50)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_predictions",
                        to="markets.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "ai_predictions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "prediction_type", "-created_at"],
                        name="ai_pred_lookup_idx",
                    )
                ],
            },
        ),
    ]
