# Generated by Django 5.1.5 on 2026-07-01 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("markets", "0002_timescaledb_hypertable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("buy_idea", "Buy idea"),
                            ("watch", "Watch"),
                            ("risk_warning", "Risk warning"),
                            ("diversify", "Diversify"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField()),
                ("confidence", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=50)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="markets.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["-created_at", "-score"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="rec_user_time_idx")],
            },
        ),
    ]
