# Generated by Django 5.1.5 on 2026-07-01 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=120)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("currency", models.CharField(db_index=True, max_length=3)),
                (
                    "importance",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=30)),
                ("event_time", models.DateTimeField(db_index=True)),
                ("actual", models.CharField(blank=True, max_length=20)),
                ("forecast", models.CharField(blank=True, max_length=20)),
                ("previous", models.CharField(blank=True, max_length=20)),
                ("unit", models.CharField(blank=True, max_length=10)),
                ("source", models.CharField(default="generated", max_length=30)),
            ],
            options={
                "db_table": "economic_events",
                "ordering": ["event_time"],
                "indexes": [
                    models.Index(fields=["event_time", "importance"], name="econ_time_imp_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency", "title", "event_time"), name="uniq_econ_event"
                    )
                ],
            },
        ),
    ]
