# Generated by Django 5.1.5 on 2026-07-01 07:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_timescaledb_hypertable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=80)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolios",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=24),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=20),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=24),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="markets.instrument",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_holdings",
                "ordering": ["instrument__symbol"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "type",
                    models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fee", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=20)),
                ("executed_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="markets.instrument",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_transactions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_portfolio_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "instrument"), name="uniq_holding_portfolio_instrument"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["portfolio", "-executed_at"], name="txn_portfolio_time_idx"),
        ),
    ]
