# Generated by Django 5.1.5 on 2026-06-26 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataProviderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50, unique=True)),
                ("domain", models.CharField(default="market", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("degraded", "Degraded"), ("down", "Down")],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("quota_used", models.PositiveIntegerField(default=0)),
                ("quota_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "data_provider_status",
                "ordering": ["provider"],
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "exchanges",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("forex", "Forex"),
                            ("commodity", "Commodity"),
                            ("index", "Index"),
                            ("ETF", "ETF"),
                            ("crypto", "Crypto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "markets",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("forex", "Forex"),
                            ("commodity", "Commodity"),
                            ("index", "Index"),
                            ("ETF", "ETF"),
                            ("crypto", "Crypto"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instruments",
                        to="markets.exchange",
                    ),
                ),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("5m", "5 minutes"),
                            ("15m", "15 minutes"),
                            ("1h", "1 hour"),
                            ("1d", "1 day"),
                        ],
                        max_length=4,
                    ),
                ),
                ("ts", models.DateTimeField(primary_key=True, serialize=False)),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
                ),
                ("source", models.CharField(default="synthetic", max_length=50)),
                (
                    "instrument",
                    models.ForeignKey(
                        db_column="instrument_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="markets.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "market_price_bars",
                "ordering": ["ts"],
            },
        ),
        migrations.CreateModel(
            name="SymbolAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("provider_symbol", models.CharField(max_length=64)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="markets.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "symbol_aliases",
            },
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(fields=["asset_class", "is_active"], name="instrument_class_idx"),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                fields=("asset_class", "symbol", "exchange"), name="uniq_instrument_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="pricebar",
            index=models.Index(
                fields=["instrument", "interval", "-ts"], name="pricebar_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="symbolalias",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_symbol"), name="uniq_provider_symbol_alias"
            ),
        ),
    ]
