# Generated by Django 5.1.5 on 2026-06-30 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="news.newscategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "news categories",
                "db_table": "news_categories",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("source", models.CharField(max_length=80)),
                ("source_url", models.TextField()),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("simhash", models.BigIntegerField(db_index=True, default=0)),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=150)),
                ("image_url", models.URLField(blank=True)),
                ("language", models.CharField(default="en", max_length=5)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("impact_score", models.PositiveSmallIntegerField(default=0)),
                ("is_breaking", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingested"),
                            ("processed", "Processed"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.newscategory",
                    ),
                ),
            ],
            options={
                "db_table": "news",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsEntity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("instrument", "Instrument"),
                            ("company", "Company"),
                            ("ticker", "Ticker"),
                            ("currency", "Currency"),
                            ("commodity", "Commodity"),
                            ("country", "Country"),
                            ("person", "Person"),
                            ("org", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_text", models.CharField(max_length=150)),
                ("linked_kind", models.CharField(blank=True, max_length=30)),
                ("linked_id", models.UUIDField(blank=True, null=True)),
                ("salience", models.FloatField(default=0.0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="news.newsarticle",
                    ),
                ),
            ],
            options={
                "db_table": "news_entities",
            },
        ),
        migrations.CreateModel(
            name="NewsSentiment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.FloatField()),
                ("confidence", models.FloatField()),
                ("analyzer", models.CharField(default="lexicon", max_length=40)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment",
                        to="news.newsarticle",
                    ),
                ),
            ],
            options={
                "db_table": "news_sentiment",
            },
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["-published_at"], name="news_published_idx"),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["-impact_score"], name="news_impact_idx"),
        ),
        migrations.AddIndex(
            model_name="newsentity",
            index=models.Index(fields=["linked_kind", "linked_id"], name="news_entity_link_idx"),
        ),
    ]
